[customizations.kernel]
append = "intel_iommu=on iommu=pt mem_sleep=s2idle pcie_ports=native"

[customizations.installer.modules]
enable = [
    "org.fedoraproject.Anaconda.Modules.Localization",
    "org.fedoraproject.Anaconda.Modules.Timezone",
]
disable = [
    "org.fedoraproject.Anaconda.Modules.Users",
    "org.fedoraproject.Anaconda.Modules.Network",
]

[customizations.installer.kickstart]
contents = """
graphical

clearpart --all
rootpw --lock --iscrypted locked

%post
bootc switch --mutate-in-place --transport registry REPLACE_WITH_IMAGE_NAME
%end
"""
